name: mhasql-th
version: 0.5.0
github: mbj/mhasql-th
category: Hasql, Database, PostgreSQL, Template Haskell
synopsis: Template Haskell integration for hasql.
description: Fork of official hasql-th with different type generation trade offs.
author: Markus Schirp <mbj@schirp-dso.com>
maintainer: Markus Schirp <mbj@schirp-dso.com>
copyright: (c) 2023 Markus Schirp, (c) 2015, Nikita Volkov
license: MIT
license-file: LICENSE

default-extensions:
- FlexibleInstances
- LambdaCase
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- QuasiQuotes
- ScopedTypeVariables
- TemplateHaskell
- TupleSections

dependencies:
- base
- bytestring
- containers
- contravariant
- foldl
- hasql
- postgresql-syntax
- tasty-mgolden
- template-haskell
- template-haskell-compat-v0208
- text
- uuid
- vector

ghc-options:
- -Wall

library:
  source-dirs: src
  exposed-modules:
    MHasql.TH
  other-modules:
    MHasql.TH.Construction.Exp
    MHasql.TH.Extraction.ChildExprList
    MHasql.TH.Extraction.Exp
    MHasql.TH.Extraction.InputTypeList
    MHasql.TH.Extraction.OutputTypeList
    MHasql.TH.Extraction.PlaceholderTypeMap
    MHasql.TH.Extraction.PrimitiveType
    MHasql.TH.Prelude

tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - cbt
    - dbt
    - devtools
    - hasql
    - mhasql-th
    - mio-core
    - mprelude
    - tasty
    - tasty-hunit
  doctest:
    source-dirs: test/doctest
    main: Main.hs
    dependencies:
    - doctest
    - mhasql-th
