name: Release the lib to Hackage

on:
  push:
    branches:
      - supermajor
      - major
      - minor
      - patch

concurrency:
  group: release
  cancel-in-progress: true

jobs:

  format:
    uses: ./.github/workflows/format.yaml
    secrets: inherit

  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit
  
  release:
    needs:
      - format
      - check
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/release.yaml@v3
    secrets: inherit
    with:
      prefix-tag-with-v: false
      docs: true
