name: Compile, test and check the docs

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  format:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/format.yaml@v2
    secrets: inherit

  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit
